### PR TITLE
- Added pause resume functions Fixes #2

### LINKED ISSUE #2: Add animation pause functionlity
It will be nice if it has an instance method that can be called to pause the animation for example i just pause an audio.

### PR DESCRIPTION
**Pull request by mzeeshanid**
Pause/Resume functionality added. [More Info](http://stackoverflow.com/questions/2306870/is-there-a-way-to-pause-a-cabasicanimation)

### CODE REVIEW

**Comment by obrhoff** [comment]
I'm not sure if pausing the CAAnimation is a good approach. The Apple implementation of it simply puts the bars down. I made a second branch with a similar behavior. Can you check if it fits the requirements?

**Comment by mzeeshanid** [comment]
I checked the new branch. Its awesome now. Thank you :)

**Comment by mzeeshanid** [comment]
As far as the approach for pausing the CAAnimation is concerned, I think its good approach as it is documented way of pausing the animation. See this:
 [Apple's technical note QA1673!](https://developer.apple.com/library/ios/qa/qa1673/_index.html)

**Comment by obrhoff** [comment]
Yes indeed. I didn't feel it would be the right approach in this case, because it would break the reusability of a TableViewCell. (The state needs to be restored when the cell if configured.)

**Pull request closed without merging**
